# Generated by Django 5.2.13 on 2026-05-27 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField()),
                ('state', models.CharField(choices=[('DRAFT', 'Draft'), ('FINALIZED', 'Finalized')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_lists_created', to=settings.AUTH_USER_MODEL)),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_lists_finalized', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_lists', to='accounts.team')),
            ],
            options={
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('default_unit', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=1)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_items', to='accounts.team')),
            ],
            options={
                'ordering': ['category', 'sort_order', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrderListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_text', models.CharField(blank=True, max_length=120)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=1)),
                ('order_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ordering.orderlist')),
                ('purchase_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='ordering.purchaseitem')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='orderlist',
            constraint=models.UniqueConstraint(fields=('team', 'order_date'), name='uniq_team_order_date'),
        ),
        migrations.AddConstraint(
            model_name='purchaseitem',
            constraint=models.UniqueConstraint(fields=('team', 'name'), name='uniq_team_purchase_item_name'),
        ),
        migrations.AddConstraint(
            model_name='orderlistitem',
            constraint=models.UniqueConstraint(fields=('order_list', 'purchase_item'), name='uniq_order_list_purchase_item'),
        ),
    ]
