# Generated by Django 5.2.12 on 2026-10-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='supplier',
            field=models.CharField(blank=True, help_text='Who you buy this from — lets an order be split and exported per supplier.', max_length=150),
        ),
    ]
