# Generated by Django 5.2.12 on 2026-09-13 16:12

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='', validators=[accounts.models.validate_avatar_size]),
        ),
    ]
