# Generated by Django 5.2.12 on 2026-09-13 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_cookprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembership',
            name='can_manage_menu',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='teammembership',
            name='can_manage_recipes',
            field=models.BooleanField(default=True),
        ),
    ]
