# Generated by Django 5.2.12 on 2026-10-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_teammembership_can_manage_menu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='accent_color',
            field=models.CharField(choices=[('blue', 'Blue'), ('forest', 'Forest'), ('amber', 'Amber'), ('plum', 'Plum'), ('slate', 'Slate')], default='blue', max_length=20),
        ),
        migrations.AddField(
            model_name='team',
            name='display_name',
            field=models.CharField(blank=True, help_text='Shown instead of the team name around the app. Purely cosmetic — join code and login are unaffected.', max_length=200),
        ),
    ]
