# Generated by Django 5.2.12 on 2026-03-20 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('menu', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrepPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField()),
                ('state', models.CharField(choices=[('DRAFT', 'Draft'), ('PRODUCTION', 'Production')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plans_created', to=settings.AUTH_USER_MODEL)),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans_finalized', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='accounts.team')),
            ],
            options={
                'ordering': ['-service_date'],
            },
        ),
        migrations.CreateModel(
            name='PlanDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.dish')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_dishes', to='planning.prepplan')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PrepTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NONE', 'None'), ('PLANNED', 'Planned'), ('DONE', 'Done')], default='NONE', max_length=20)),
                ('daily_note', models.TextField(blank=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dish_component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.dishcomponent')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='planning.prepplan')),
            ],
        ),
        migrations.AddConstraint(
            model_name='prepplan',
            constraint=models.UniqueConstraint(fields=('team', 'service_date'), name='uniq_team_plan_date'),
        ),
        migrations.AddConstraint(
            model_name='plandish',
            constraint=models.UniqueConstraint(fields=('plan', 'dish'), name='uniq_plan_dish'),
        ),
        migrations.AddIndex(
            model_name='preptask',
            index=models.Index(fields=['plan', 'status'], name='planning_pr_plan_id_a73cfa_idx'),
        ),
        migrations.AddConstraint(
            model_name='preptask',
            constraint=models.UniqueConstraint(fields=('plan', 'dish_component'), name='uniq_plan_dishcomponent_task'),
        ),
    ]
