# Generated by Django 5.2.13 on 2026-09-11 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prepplan',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prepplan',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans_completed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prepplan',
            name='state',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PRODUCTION', 'Production'), ('COMPLETE', 'Complete')], default='DRAFT', max_length=20),
        ),
    ]
