# Generated by Django 5.2.12 on 2026-09-13 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_remove_component_spec_text_remove_component_type_and_more'),
        ('planning', '0002_prepplan_completed_at_prepplan_completed_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='preptask',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='standalone_tasks', to='menu.component'),
        ),
        migrations.AddField(
            model_name='preptask',
            name='manual_label',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='preptask',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adhoc_tasks', to='menu.recipe'),
        ),
        migrations.AlterField(
            model_name='preptask',
            name='dish_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='menu.dishcomponent'),
        ),
        migrations.AddConstraint(
            model_name='preptask',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('component__isnull', True), ('dish_component__isnull', False), ('manual_label', ''), ('recipe__isnull', True)), models.Q(('component__isnull', False), ('dish_component__isnull', True), ('manual_label', ''), ('recipe__isnull', True)), models.Q(('component__isnull', True), ('dish_component__isnull', True), ('manual_label', ''), ('recipe__isnull', False)), models.Q(('component__isnull', True), ('dish_component__isnull', True), ('recipe__isnull', True), models.Q(('manual_label', ''), _negated=True)), _connector='OR'), name='prep_task_exactly_one_origin'),
        ),
    ]
