# Generated by Django 5.2.12 on 2026-09-13 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='on_use',
            new_name='is_active',
        ),
    ]
