# Generated by Django 5.2.12 on 2026-09-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_rename_on_use_dish_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='spec_text',
        ),
        migrations.RemoveField(
            model_name='component',
            name='type',
        ),
        migrations.AddField(
            model_name='component',
            name='standalone_active',
            field=models.BooleanField(default=False),
        ),
    ]
